experimentName: ContrastiveLearning-WorkloadClassification
searchSpaceFile: ./searchspace/CL_classifier_searchspace.json
trialCommand: python CL_classifier.py
trialCodeDirectory: .
trialGpuNumber: 1
trialConcurrency: 5
maxTrialNumber: 150
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
assessor:
  name: Medianstop
  classArgs:
    optimize_mode: maximize
    start_step: 5
trainingService:
  platform: local
  useActiveGpu: True